version: '3.8'

services:
  mongodb:
    image: mongo:latest
    network_mode: bridge
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=velada-2024
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: